version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: tests/integration/Dockerfile.test
    volumes:
      - ./tests:/app/tests
      - ./coverage:/app/coverage
    environment:
      - NODE_ENV=test
      - LOG_LEVEL=info
      - TEST_TIMEOUT=60000
    networks:
      - juicetokens-test-net

  prometheus:
    image: prom/prometheus:v2.30.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - test
    networks:
      - juicetokens-test-net

  grafana:
    image: grafana/grafana:8.2.2
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    networks:
      - juicetokens-test-net

networks:
  juicetokens-test-net:
    driver: bridge 