version: '3.8'

services:
  web:
    build: .
    ports:
      - "4242:4242"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    networks:
      - juicetokens-test

networks:
  juicetokens-test:
    driver: bridge 